version: '2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    build:
      context: kibana/
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge

